# Reference: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Contributing Policy
    url: https://github.com/mrmap-community/mrmap/blob/develop/CONTRIBUTING.md
    about: Please read through our contributing policy before opening an issue or pull request
  - name: ðŸ’¬ Discussion Group
    url: https://github.com/mrmap-community/mrmap/discussions
    about: Join our discussion group for assistance with installation issues and other problems
