name: Build and Publishing docs on github pages
on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened]

jobs:
  build-docs:
    name: build docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      # Install all system dependencies for the MrMap project
      # ===============================
      - name: Install System Dependencies for MrMap project
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          libssl-dev \
          libcurl4-openssl-dev \
          gdal-bin
      # Install sphinx local
      # ===============================
      - name: Install sphinx
        run: |
          sudo apt-get install python3-sphinx
      # Upgrade pip, setuptools and wheel
      # ===============================
      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install pip dependencies
        run: |
            pip3 install -r ./backend/requirements.txt && pip3 install -r ./docs/requirements.txt
      # ===============================
      # Build documentation
      # ===============================
      - name: build documentation
        run: |
          export $(grep -v '^#' ./docs/.docs.env | xargs)
          MRMAP_MEDIA_DIR=./tmp sphinx-multiversion docs/source docs/build/html -b linkcheck -D smv_branch_whitelist='${{ github.head_ref }}'
          MRMAP_MEDIA_DIR=./tmp sphinx-multiversion docs/source docs/build/html -b html -E -D smv_branch_whitelist='${{ github.head_ref }}'

      - name: upload build reports
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs/build

  publish-docs:
    needs: [build-docs]
    name: publish docs
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/master' && github.ref == 'refs/heads/master' && github.event_name != 'push' }}
    steps:
      - name: download coverage reports
        uses: actions/download-artifact@v2
        with: 
          name: docs
          path: ./docs/build
      # ===============================
      # Publish built docs to gh-pages branch.
      # ===============================
      - name: Commit documentation changes
        run: |
            git clone https://github.com/${GITHUB_REPOSITORY}.git --branch gh-pages --single-branch gh-pages
            cp -r docs/build/html/* gh-pages/
            cd gh-pages
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update documentation" -a || true
            # The above command will fail if no changes were present, so we ignore
            # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
        # ===============================
